# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20160831_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head_img',
            field=models.ImageField(default=0, upload_to='', verbose_name='文章标题图片'),
            preserve_default=False,
        ),
    ]
