# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20160831_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='创建时间'),
        ),
    ]
