# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_auto_20160831_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='文章标题图片'),
        ),
    ]
