# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_auto_20160907_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(default=1, upload_to='uploads', verbose_name='文章标题图片'),
            preserve_default=False,
        ),
    ]
