# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_auto_20160910_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commet',
            new_name='comment',
        ),
    ]
